version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sumir-traders
      POSTGRES_PASSWORD: sumir-traders-be-123
      POSTGRES_DB: sumir-traders
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
